language: php
php:
  - 5.6

language: php
php:
  - '5.6'

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - phpunit test/TestTarjeta.php
  
notifications:
  email: false
